name: Feature Request
description: Suggest a new feature or enhancement for Octofer
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the motivation?
      placeholder: Describe the problem or use case this feature addresses...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: Describe how you envision this feature working...
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple - Minor change or addition
        - Medium - Moderate development effort
        - Complex - Significant development effort
        - Unknown - Not sure
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be valuable.
      placeholder: |
        1. When managing deployments across multiple teams...
        2. During emergency situations where...
        3. For compliance requirements that...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples.
      placeholder: Any additional information, links to similar features in other tools, etc.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: I have considered how this feature fits with Frezze's existing functionality
          required: true

