name: Security Issue
description: Report a security vulnerability
title: "[Security]: "
labels: ["security", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ **CRITICAL SECURITY VULNERABILITIES**

        **For critical security vulnerabilities, please DO NOT use this issue template.**

        Instead, please report critical security issues directly to the maintainer via:
        - Private GitHub Security Advisory
        - Email to the project maintainer

        This template is for **non-critical security concerns** that can be discussed publicly.

  - type: checkboxes
    id: severity-confirmation
    attributes:
      label: Severity Confirmation
      description: Please confirm this is not a critical security vulnerability
      options:
        - label: This is NOT a critical security vulnerability that could lead to immediate compromise
          required: true
        - label: I understand that critical vulnerabilities should be reported privately
          required: true

  - type: dropdown
    id: security-type
    attributes:
      label: Security Issue Type
      description: What type of security concern is this?
      options:
        - Information disclosure (non-sensitive)
        - Authentication/authorization improvement
        - Input validation concern
        - Configuration security
        - Dependency security concern
        - Security hardening suggestion
        - Security documentation issue
        - Other non-critical security concern
    validations:
      required: true

  - type: textarea
    id: security-summary
    attributes:
      label: Security Issue Summary
      description: Briefly describe the security concern.
      placeholder: Describe the security issue without revealing exploit details...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could happen if this security concern is not addressed?
      placeholder: Describe the potential impact on users, data, or system security...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Estimated Severity
      description: How severe is this security concern?
      options:
        - Low - Minimal impact
        - Medium - Moderate impact
        - High - Significant impact (but not critical)
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Demonstrate
      description: How can this security concern be demonstrated? (Avoid providing full exploit details)
      placeholder: |
        1. General steps to observe the behavior
        2. What to look for
        3. Expected vs actual security behavior

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Environment where this was observed
      placeholder: |
        - Frezze version:
        - Deployment type:
        - Configuration details (non-sensitive):

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to address this security concern?
      placeholder: Potential fixes, workarounds, or improvements...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant security documentation, standards, or similar issues.
      placeholder: |
        - OWASP guidelines
        - GitHub security best practices
        - Related CVEs or security advisories

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information.
      placeholder: Additional context, related security concerns, etc.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have confirmed this is not a critical vulnerability requiring private disclosure
          required: true
        - label: I have not included full exploit details or proof-of-concept code
          required: true
        - label: I have checked existing issues to avoid duplicates
          required: true

